InsuranceSite/urls.py
from django.conf.urls import patterns, include, url
# from django.contrib import admin

urlpatterns = patterns(
    '',

    url(r'^$', 'bms.views.index', name='home'),                   # 默认首页
    url(r'^auth/', include('authentic.urls', namespace='authentic')),       # 认证模块
    url(r'^bms/', include('bms.urls', namespace='bms')),                        # 后台管理模块
    url(r'^pss/', include('pss.urls', namespace='pss')),                        # 手机端接口
    url(r'^wss/', include('wss.urls', namespace='wss')),                        # 微信端数据交互
    url(r'^cos/', include('cos.urls', namespace='cos')),                        # 给保险公司人员查看订单
)

bms/templates/bms/product/urls.py
    url(r'^user/transport_detail/(?P<transport_id>\w{24})/$', 'bms.views_user.transport_detail', name='transport_detail'),
    url(r'^user/transport_edit/(?P<transport_id>\w{24})/$', 'bms.views_user.transport_edit', name='transport_edit'),

    #司机
    url(r'^user/driver/(?P<page_index>\d+)/$', 'bms.views_user.driver_list', name='driver_list'),
    url(r'^user/driver_detail/(?P<driver_id>\w{24})/$', 'bms.views_user.driver_detail', name='driver_detail'),
    url(r'^user/driver_edit/(?P<driver_id>\w{24})/$', 'bms.views_user.driver_edit', name='driver_edit'),

    #货主
    url(r'^user/boss/(?P<page_index>\d+)/$', 'bms.views_user.boss_list', name='boss_list'),
    url(r'^user/boss_detail/(?P<boss_id>\w{24})/$', 'bms.views_user.boss_detail', name='boss_detail'),
    url(r'^user/boss_edit/(?P<boss_id>\w{24})/$', 'bms.views_user.boss_edit', name='boss_edit'),
    #
    #理赔人员
    url(r'^user/claim/(?P<page_index>\d+)/$', 'bms.views_user.claim_list', name='claim_list'),
    url(r'^user/claim_detail/(?P<claim_id>\w{24})/$', 'bms.views_user.claim_detail', name='claim_detail'),
    url(r'^user/claim_edit/(?P<claim_id>\w{24})/$', 'bms.views_user.claim_edit', name='claim_edit'),
    url(r'^user/claim_create/$', 'bms.views_user.claim_create', name='claim_create'),
    # url(r'^user/claim_delete/(?P<claim_id>\w{24})/$', 'bms.views_user.claim_delete', name='claim_delete'),
    #
    #律师
    url(r'^user/lawyer/(?P<page_index>\d+)/$', 'bms.views_user.lawyer_list', name='lawyer_list'),
    url(r'^user/lawyer_detail/(?P<lawyer_id>\w{24})/$', 'bms.views_user.lawyer_detail', name='lawyer_detail'),
    url(r'^user/lawyer_edit/(?P<lawyer_id>\w{24})/$', 'bms.views_user.lawyer_edit', name='lawyer_edit'),
    url(r'^user/lawyer_create/$', 'bms.views_user.lawyer_create', name='lawyer_create'),
    # url(r'^user/lawyer_delete/(?P<lawyer_id>\w{24})/$', 'bms.views_user.lawyer_delete', name='lawyer_delete'),

    ########                产品管理               ########
    ####    保险总公司
    url(r'^product/head_company/(?P<page_index>\d+)/$', 'bms.views_product.head_company_list', name='head_company_list'),
    url(r'^product/head_company_detail/(?P<head_company_id>\w{24})/$', 'bms.views_product.head_company_detail', name='head_company_detail'),
    url(r'^product/head_company_edit/(?P<head_company_id>\w{24})/$', 'bms.views_product.head_company_edit', name='head_company_edit'),
    url(r'^product/head_company_create/$', 'bms.views_product.head_company_create', name='head_company_create'),

    ####    保险分公司
    url(r'^product/tail_company/(?P<page_index>\d+)/$', 'bms.views_product.tail_company_list', name='tail_company_list'),
    url(r'^product/tail_company_detail/(?P<tail_company_id>\w{24})/$', 'bms.views_product.tail_company_detail', name='tail_company_detail'),
    url(r'^product/tail_company_edit/(?P<tail_company_id>\w{24})/$', 'bms.views_product.tail_company_edit', name='tail_company_edit'),
    url(r'^product/tail_company_create/$', 'bms.views_product.tail_company_create', name='tail_company_create'),
    ###    产品
    url(r'^product/insurance_product/(?P<page_index>\d+)/$', 'bms.views_product.insurance_product_list', name='insurance_product_list'),
    url(r'^product/insurance_product_detail/(?P<insurance_product_id>\w{24})/$', 'bms.views_product.insurance_product_detail', name='insurance_product_detail'),
    url(r'^product/insurance_product_edit/(?P<insurance_product_id>\w{24})/$', 'bms.views_product.insurance_product_edit', name='insurance_product_edit'),
    url(r'^product/insurance_product_create/$', 'bms.views_product.insurance_product_create', name='insurance_product_create'),
    #       为产品新增文档
    url(r'^product/insurance_product_create_document/(?P<insurance_product_id>\w{24})/(?P<company_id>\w{24})/$', 'bms.views_product.insurance_product_create_document', name='insurance_product_create_document'),
    url(r'^product/insurance_product_delete_document/(?P<insurance_product_id>\w{24})/(?P<document_id>\w{24})/$', 'bms.views_product.insurance_product_delete_document', name='insurance_product_delete_document'),

    ###    产品
    url(r'^insurance/coupon/(?P<page_index>\d+)/$', 'bms.views_product.coupon_list', name='coupon_list'),
    # url(r'^coupon/insurance_coupon_detail/(?P<insurance_coupon_id>\w{24})/$', 'bms.views_product.insurance_coupon_detail', name='insurance_coupon_detail'),
    # url(r'^coupon/insurance_coupon_edit/(?P<insurance_coupon_id>\w{24})/$', 'bms.views_product.insurance_coupon_edit', name='insurance_coupon_edit'),
    # url(r'^coupon/insurance_coupon_create/$', 'bms.views_product.insurance_coupon_create', name='insurance_coupon_create'),

    ####    订单
    url(r'^insurance/order/(?P<page_index>\d+)/$', 'bms.views_order.order_list', name='order_list'),
    url(r'^insurance/order_detail/(?P<order_id>\w{24})/$', 'bms.views_order.order_detail', name='order_detail'),
    url(r'^insurance/order_edit/(?P<order_id>\w{24})/$', 'bms.views_order.order_edit', name='order_edit'),
    url(r'^insurance/order_create/$', 'bms.views_order.order_create', name='order_create'),
    #付款
    url(r'^insurance/order_pay/(?P<order_id>\w{24})/$', 'bms.views_order.order_pay', name='order_pay'),
    # ####    屏蔽保单
    # url(r'^insurance/policy/hidden/(?P<policy_id>\w{24})/$', 'bms.views_product.policy_hidden', name='policy_hidden'),


    # url(r'^insurance/company_delete/(?P<company_id>\w{24})/$', 'bms.views_insurance.company_delete', name='company_delete'),
    ####    投保文档的修改和新增
    # url(r'^insurance/company/document/save/(?P<company_id>\w{24})/$', 'bms.views_insurance.company_document_save', name='company_document_save'),

    ####    保险文档
    url(r'^insurance/document/(?P<page_index>\d+)/$', 'bms.views_product.insurance_document_list', name='insurance_document_list'),
    url(r'^insurance/document_detail/(?P<document_id>\w{24})/$', 'bms.views_product.insurance_document_detail', name='insurance_document_detail'),
    url(r'^insurance/document_edit/(?P<document_id>\w{24})/$', 'bms.views_product.insurance_document_edit', name='insurance_document_edit'),
    url(r'^insurance/document_create/$', 'bms.views_product.insurance_document_create', name='insurance_document_create'),
    # # url(r'^insurance/document_delete/(?P<document_id>\w{24})/$', 'bms.views_insurance.document_delete', name='document_delete'),
    ####    预览文档内容
    url(r'^insurance/document/preview/(?P<document_id>\w{24})/$', 'bms.views_product.insurance_document_preview', name='insurance_document_preview'),
    ####        赔案
    url(r'^insurance/compensate/(?P<page_index>\d+)/$', 'bms.views_compensate.compensate_list', name='compensate_list'),
    url(r'^insurance/compensate_detail/(?P<compensate_id>\w{24})/$', 'bms.views_compensate.compensate_detail', name='compensate_detail'),
    #
    # ########               互动信息 interactive                #############################################################################################
    #
    # ####    意见和建议
    # url(r'^interactive/suggestions/(?P<page_index>\d+)/$', 'bms.views_interactive.suggestions_list', name='suggestions_list'),
    # url(r'^interactive/suggestions/(?P<suggestions_id>\w{24})/$', 'bms.views_interactive.suggestions_detail', name='suggestions_detail'),

    ########                异常管理 exception                ########
    # 异常 exception
    url(r'^exception/(?P<page_index>\d+)/$', 'bms.views_exception.exception_list', name='exception_list'),
    url(r'^exception/(?P<exception_id>\w{24})/$', 'bms.views_exception.exception_detail', name='exception_detail'),
    url(r'^exception/new/$', 'bms.views_exception.new_exception_detail', name='new_exception_detail'),
    url(r'^exception/delete/(?P<exception_id>\w{24})/$', 'bms.views_exception.exception_delete', name='exception_delete'),
    url(r'^exception/delete/all/$', 'bms.views_exception.exception_delete_all', name='exception_delete_all'),
    url(r'^exception/delete/similar/(?P<exception_id>\w{24})/$', 'bms.views_exception.exception_delete_similar', name='exception_delete_similar'),


    ########                系统日志 logs                ########
    # 系统日志日志 logs
    url(r'^logs/(?P<page_index>\d+)/$', 'bms.views_log.log_list', name='log_list'),
    url(r'^logs/(?P<log_id>\w{24})/$', 'bms.views_log.log_detail', name='log_detail'),
    url(r'^logs/delete/(?P<log_id>\w{24})/$', 'bms.views_log.log_delete', name='log_delete'),
    url(r'^logs/delete/all/$', 'bms.views_log.log_delete_all', name='log_delete_all'),

    # 微信事件日志 wechat event wechat_events
    url(r'^wechat/event/(?P<page_index>\d+)/$', 'bms.views_log.wechat_event_list', name='wechat_event_list'),
    url(r'^wechat/event/(?P<wechat_event_id>\w{24})/$', 'bms.views_log.wechat_event_detail', name='wechat_event_detail'),
    url(r'^wechat/event/delete/(?P<wechat_event_id>\w{24})/$', 'bms.views_log.wechat_event_delete', name='wechat_event_delete'),
    url(r'^wechat/event/delete/all/$', 'bms.views_log.wechat_event_delete_all', name='wechat_event_delete_all'),

    ########                服务器设置管理 settings                ########
    # 设置 settings
    url(r'^settings/$', 'bms.views_settings.settings_index', name='settings'),
    url(r'^settings/base/$', 'bms.views_settings.settings_base', name='settings_base'),
    url(r'^settings/database/$', 'bms.views_settings.settings_database', name='settings_database'),
    url(r'^settings/database/save/$', 'bms.views_settings.settings_database_save', name='settings_database_save'),
    url(r'^settings/debug/$', 'bms.views_settings.debug_model', name='setting_debug_model'),


    # 位置 locations
    url(r'^interface/locations/get_insurance_company_list/$', 'bms.views_interface.get_insurance_company_list', name='get_insurance_company_list'),
    url(r'^interface/locations/get_insurance_type_list/$', 'bms.views_interface.get_insurance_type_list', name='get_insurance_type_list'),
    #添加货物类型
    url(r'^interface/locations/get_insurance_product_list$', 'bms.views_interface.get_insurance_product_list', name='get_insurance_product_list'),

    ##### 测试专用

bms/urls.py
    url(r'^insurance/compensate_detail/(?P<compensate_id>\w{24})/$', 'bms.views_compensate.compensate_detail', name='compensate_detail'),
    #
    # ########               互动信息 interactive                #############################################################################################
    #
    # ####    意见和建议
    # url(r'^interactive/suggestions/(?P<page_index>\d+)/$', 'bms.views_interactive.suggestions_list', name='suggestions_list'),
    # url(r'^interactive/suggestions/(?P<suggestions_id>\w{24})/$', 'bms.views_interactive.suggestions_detail', name='suggestions_detail'),

    ########               微信公众号管理 宣传推广               #####################################################

    ####    物流公司
    url(r'^campaign/logistics_list/(?P<page_index>\d+)/$', 'bms.views_campaign.logistics_list', name='logistics_list'),
    url(r'^campaign/logistics_detail/(?P<logistics_id>\w{24})/$', 'bms.views_campaign.logistics_detail', name='logistics_detail'),
    url(r'^campaign/logistics_edit/(?P<logistics_id>\w{24})/$', 'bms.views_campaign.logistics_edit', name='logistics_edit'),
    url(r'^campaign/logistics_create/$', 'bms.views_campaign.logistics_create', name='logistics_create'),
    url(r'^campaign/logistics_delete/(?P<logistics_id>\w{24})/$', 'bms.views_campaign.logistics_delete', name='logistics_delete'),
    #增加物流公司图片
    url(r'^campaign/add_logistics_pic/(?P<logistics_id>\w{24})/$', 'bms.views_campaign.add_logistics_pic', name='add_logistics_pic'),
    # 修改单个物流公司图片
    url(r'^campaign/edit_logistics_pic/(?P<logistics_id>\w{24})/$', 'bms.views_campaign.edit_logistics_pic', name='edit_logistics_pic'),
    # 删除单个物流公司图片信息
    url(r'^campaign/delete_logistics_pic/(?P<logistics_id>\w{24})/$', 'bms.views_campaign.delete_logistics_pic', name='delete_logistics_pic'),

    url(r'^campaign/campaign_lawyer_list/(?P<page_index>\d+)/$', 'bms.views_campaign.campaign_lawyer_list', name='campaign_lawyer_list'),
    url(r'^campaign/campaign_lawyer_detail/(?P<campaign_lawyer_id>\w{24})/$', 'bms.views_campaign.campaign_lawyer_detail', name='campaign_lawyer_detail'),
    url(r'^campaign/campaign_lawyer_edit/(?P<campaign_lawyer_id>\w{24})/$', 'bms.views_campaign.campaign_lawyer_edit', name='campaign_lawyer_edit'),
    url(r'^campaign/campaign_lawyer_create/$', 'bms.views_campaign.campaign_lawyer_create', name='campaign_lawyer_create'),
    url(r'^campaign/campaign_lawyer_delete/(?P<campaign_lawyer_id>\w{24})/$', 'bms.views_campaign.campaign_lawyer_delete', name='campaign_lawyer_delete'),
    # 宣传推广-司机
    url(r'^campaign/driver_list/(?P<page_index>\d+)/$', 'bms.views_campaign.driver_list', name='campaign_driver_list'),
    url(r'^campaign/driver_create/$', 'bms.views_campaign.driver_create', name='campaign_driver_create'),
    url(r'^campaign/driver_delete/(?P<driver_id>\w{24})/$', 'bms.views_campaign.driver_delete', name='campaign_driver_delete'),
    url(r'^campaign/driver_detail/(?P<driver_id>\w{24})/$', 'bms.views_campaign.driver_detail', name='campaign_driver_detail'),
    url(r'^campaign/driver_edit/(?P<driver_id>\w{24})/$', 'bms.views_campaign.driver_edit', name='driver_edit_test'),
#     url(r'^campaign/related_user/$', 'bms.views_campaign.related_user', name='related_user'),
#     url(r'^campaign/cancel_related_user/$', 'bms.views_campaign.cancel_related_user', name='cancel_related_user'),




    ########                异常管理 exception                ########
    # 异常 exception
    url(r'^exception/(?P<page_index>\d+)/$', 'bms.views_exception.exception_list', name='exception_list'),
    url(r'^exception/(?P<exception_id>\w{24})/$', 'bms.views_exception.exception_detail', name='exception_detail'),
    url(r'^exception/new/$', 'bms.views_exception.new_exception_detail', name='new_exception_detail'),
    url(r'^exception/delete/(?P<exception_id>\w{24})/$', 'bms.views_exception.exception_delete', name='exception_delete'),
    url(r'^exception/delete/all/$', 'bms.views_exception.exception_delete_all', name='exception_delete_all'),
    url(r'^exception/delete/similar/(?P<exception_id>\w{24})/$', 'bms.views_exception.exception_delete_similar', name='exception_delete_similar'),


    ########                系统日志 logs                ########
    # 系统日志日志 logs
    url(r'^logs/(?P<page_index>\d+)/$', 'bms.views_log.log_list', name='log_list'),
    url(r'^logs/(?P<log_id>\w{24})/$', 'bms.views_log.log_detail', name='log_detail'),
    url(r'^logs/delete/(?P<log_id>\w{24})/$', 'bms.views_log.log_delete', name='log_delete'),
    url(r'^logs/delete/all/$', 'bms.views_log.log_delete_all', name='log_delete_all'),

    # 微信事件日志 wechat event wechat_events
    url(r'^wechat/event/(?P<page_index>\d+)/$', 'bms.views_log.wechat_event_list', name='wechat_event_list'),
    url(r'^wechat/event/(?P<wechat_event_id>\w{24})/$', 'bms.views_log.wechat_event_detail', name='wechat_event_detail'),
    url(r'^wechat/event/delete/(?P<wechat_event_id>\w{24})/$', 'bms.views_log.wechat_event_delete', name='wechat_event_delete'),
    url(r'^wechat/event/delete/all/$', 'bms.views_log.wechat_event_delete_all', name='wechat_event_delete_all'),

    ########                服务器设置管理 settings                ########
    # 设置 settings
    url(r'^settings/$', 'bms.views_settings.settings_index', name='settings'),
    url(r'^settings/base/$', 'bms.views_settings.settings_base', name='settings_base'),
    url(r'^settings/database/$', 'bms.views_settings.settings_database', name='settings_database'),
    url(r'^settings/database/save/$', 'bms.views_settings.settings_database_save', name='settings_database_save'),
    url(r'^settings/debug/$', 'bms.views_settings.debug_model', name='setting_debug_model'),
    #用户协议
    url(r'^settings/user/protocol/$', 'bms.views_settings.user_protocol', name='settings_user_protocol'),
    url(r'^settings/user/protocol/preview/$', 'bms.views_settings.user_protocol_preview', name='settings_user_protocol_preview'),
    #物流平台设置
    url(r'^settings/platform/$', 'bms.views_settings.settings_platform', name='settings_platform'),
    url(r'^settings/edit_platform/$', 'bms.views_settings.edit_platform', name='edit_platform'),
    
    #保险平台设置
     url(r'^settings/insurance_platform/$', 'bms.views_settings.insurance_platform', name='insurance_platform'),
     url(r'^settings/edit_insurance/(?P<platform_id>\w{24})/$', 'bms.views_settings.edit_insurance', name='edit_insurance'),
     url(r'^settings/insurance_delete/(?P<platform_id>\w{24})/$', 'bms.views_settings.insurance_delete', name='insurance_delete'),
    
    #平台产品维护
    url(r'^settings/platform_product/$', 'bms.views_settings.platform_product', name='platform_product_list'),
    url(r'^settings/platform_product_create/$', 'bms.views_settings.platform_product_create', name='platform_product_save'),
    url(r'^settings/platform_product_delete/(?P<product_id>\w{24})/$', 'bms.views_settings.platform_product_delete', name='platform_product_delete'),
    url(r'^settings/platform_product_detail/(?P<product_id>\w{24})/$', 'bms.views_settings.platform_product_detail', name='platform_product_detail'),
    url(r'^settings/platform_product_edit/(?P<product_id>\w{24})/$', 'bms.views_settings.platform_product_edit', name='platform_product_edit'),
    url(r'^settings/uploadImg/$', 'bms.views_settings.uploadImg', name='uploadImg'),
    
    # 位置 locations
    url(r'^interface/locations/get_insurance_company_list/$', 'bms.views_interface.get_insurance_company_list', name='get_insurance_company_list'),
    url(r'^interface/locations/get_insurance_type_list/$', 'bms.views_interface.get_insurance_type_list', name='get_insurance_type_list'),
    #添加货物类型
    url(r'^interface/locations/get_insurance_product_list$', 'bms.views_interface.get_insurance_product_list', name='get_insurance_product_list'),
    #添加包装方式
    url(r'^interface/locations/get_pack_detail_list', 'bms.views_interface.get_pack_detail_list', name='get_pack_detail_list'),
    #test获取货物详情
    url(r'^interface/locations/get_product_cargo_list', 'bms.views_interface.get_product_cargo_list', name='get_product_cargo_list'),
    #获取城市列表
    url(r'^interface/locations/get_city_list', 'bms.views_interface.get_city_list', name='get_city_list'),
    #获取县/区列表
    url(r'^interface/locations/get_dist_list', 'bms.views_interface.get_dist_list', name='get_dist_list'),
    #获取货物大类对应小类货物详情
    url(r'^interface/locations/get_cargo_detail_list', 'bms.views_interface.get_cargo_detail_list', name='get_cargo_detail_list'),
    #产品详情页面，产品货物小类回显
    url(r'^interface/locations/get_cargo_type_list', 'bms.views_interface.get_cargo_type_list', name='get_cargo_type_list'),

    ########                通用工具 tools                ########
    # 转到详细页
    url(r'^tools/(?P<item_id>\w{24})/$', 'bms.views_tools.item_detail', name='item_detail'),

    ##### 测试专用
    url(r'^test/$', 'bms.views_test.test', name='test'),
    
    ########                数据统计部分               ########
    # 转到详细页
    url(r'^statistics/insurance_amount/$', 'bms.views_statistics.insurance_amount', name='insurance_amount'),
    
    ########                车辆统计               ########
    # 转到详细页
    url(r'^car/car_list/(?P<page_index>\d+)/$', 'bms.views_car.car_list', name='car_list'),
    url(r'^car/car_create/$', 'bms.views_car.car_create', name='car_create'),
    url(r'^car/car_detail/(?P<car_id>\w{24})/$', 'bms.views_car.car_detail', name='car_detail'),
    url(r'^car/car_certificate/(?P<car_id>\w{24})/$', 'bms.views_car.car_certificate', name='car_certificate'),
    url(r'^car/car_delete/(?P<car_id>\w{24})/$', 'bms.views_car.car_delete', name='car_delete'),
    url(r'^car/car_edit/(?P<car_id>\w{24})/$', 'bms.views_car.car_edit', name='car_edit'),
    # 修改单个车辆图片
    url(r'^car/edit_car_pic/(?P<car_id>\w{24})/$', 'bms.views_car.edit_car_pic', name='edit_car_pic'),
    #返还油卡
    url(r'^car/car_oil_card/(?P<car_id>\w{24})/$', 'bms.views_car.car_oil_card', name='car_oil_card'),
        #货物类型入口
    url(r'^product/cargo_intry/(?P<page_index>\d+)$', 'bms.views_product.cargo_intry', name='cargo_intry'),

bms/templates/bms/log/system/exception/base_exception.html
{% extends 'bms/log/base_log.html' %}
{% load static %}
{% block title %} 异常管理 {% endblock %}
{% block level_1 %}in{% endblock %}
{% block bms_exception %}active{% endblock %}

{% block script_block %}
    <script src="{% static 'js/JSON-js-master/json2.js' %}"></script>
    <script src="{% static 'js/google-code-prettify/run_prettify.js' %}?autoload=true" defer="defer"></script>
{% endblock %}



bms/templates/bms/log/system/exception/exception_list.html
{% extends 'bms/log/system/exception/base_exception.html' %}
{% load static %}
{% load legoo_tag %}

{% block page_top %}
    <div class="row">
        <div class="col-sm-12">
            <form id="exception_search_form" class="form-inline" role="form" method="post" action="{% url 'bms:exception_list' '1' %}"> {% csrf_token %}
                <div class="input-group">
                    <label class="sr-only" for="management_exception_search">management_exception_search</label>
                    <input type="text" class="form-control" id="search_keyword" placeholder="请输入搜索关键字" name="search_keyword" value="{{ search_keyword }}" maxlength="30">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i> 搜索</button>
                        <button id="cancel_search" type="button" class="btn btn-default"><i class="fa fa-times"></i> 取消</button>
                    </span>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            {% if search_keyword and search_keyword != ''%}
            <p></p>
            <div class="alert alert-warning">
                <p>关键字： “{{ search_keyword }}”， 搜索结果：{{ paging.item_count }}</p>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            {% if paging.total_pages_count > 0 %}
            <ul class="pagination">
                <li><a href="{% url 'bms:exception_list' paging.prev_page %}">&laquo;</a></li>
                {% for page in paging.pages %}
                    <li {% if page == paging.page_index %}class="active"{% endif %}><a href="{% url 'bms:exception_list' page %}">{{ page }}</a></li>
                {% endfor %}
                <li><a href="{% url 'bms:exception_list' paging.next_page %}">&raquo;</a></li>
                <div class="clearfix"></div>
                <p>
                    第{{ paging.page_index }}页/共{{ paging.total_pages_count }}页 &nbsp;&nbsp;&nbsp;&nbsp;

                    <a href="{% url 'bms:exception_list' '1' %}">首页</a> / <a href="{% url 'bms:exception_list' paging.total_pages_count %}">尾页</a>
                </p>
            </ul>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <a class="btn btn-success pull-right" href="{% url 'bms:new_exception_detail' %}"><i class="fa fa-edit"></i>最新异常</a>
            <button class="btn btn-danger pull-right" type="button" data-toggle="modal" data-target="#delete_exception_modal"><i class="fa fa-trash-o"></i> 删除所有</button>
        </div>

    </div>
{% endblock %}


{% block page_middle %}
    {% if message and message != '' %}
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-warning">{{ message }}</div>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-sm-12">
            <div class="list-group" id="notice_group">
                <input type="hidden" id="page_index" name="page_index" value="{{ page_index }}"/>
                    {% for exception in exceptions %}
                        <a href="{% url 'bms:exception_detail' exception.id %}" class="list-group-item">
                            <div class="row">
                                <div class="col-sm-9">
                                    <h3 class="list-group-item-heading"><strong>{{ exception.exception }}</strong></h3>
                                </div>
                                <div class="col-sm-3">
                                    <p class="list-group-item-text">创建日期：{{ exception.create_time|date:'Y年m月d日 H:i:s' }}</p>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
       </div>
    </div>
{% endblock %}


{% block page_bottom %}
 <div class="modal fade" id="delete_exception_modal" tabindex="-1" role="dialog" >
    <div class="modal-dialog">
        <form id="delete_exception_form" class="form" method="post" action="{% url 'bms:exception_delete_all' %}"  >  {% csrf_token %}
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title"><i class="fa fa-trash-o"></i> 删除所有异常</h4>
              </div>
              <div class="modal-body">
                      <input type="hidden" id="id_keyword" name="keyword" value="{{ search_keyword }}">
                <div class="form-group" >
                    <label class="control-label">删除后不可恢复，是否确认删除？</label>
                </div>
              </div>
              <div class="modal-footer">
                <button class="btn btn-danger" type="submit" ><i class="fa fa-trash-o"></i> 删 除</button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> 退 出</button>
              </div>
            </div>
        </form>
    </div>
 </div>

{% endblock %}


{% block script_block %}
    <script type="text/javascript">

        //“全部”按钮的响应事件，清空搜索关键字，然后提交搜索
        $('#cancel_search').click(function(event) {
            console.log("click cancel_search");
            $('#search_keyword').val('');
            $('#exception_search_form').submit();
          })

    </script>
{% endblock %}